# crypto/level3_mlkem.py — Level 3 TQR encryption: ML-KEM-768 (FIPS 203) + AES-256-GCM hybrid.
# Single responsibility: PQC key encapsulation via ML-KEM-768 and symmetric message
# encryption via AES-256-GCM using the encapsulated shared secret.
# No QKD key or KME contact required — this module is fully self-contained.
# Used automatically when recipient_check.py flags a non-QuMail endpoint (TQR downgrade),
# or when the user manually selects Level 3.
# Do not import from transport/, ui/, mime/, portal/, or certificates/.
# Do not implement Level 1 or Level 2 logic here.

import os

import oqs
from cryptography.hazmat.primitives.ciphers.aead import AESGCM


# -------------------------------------------------------------------------
# Constants
# -------------------------------------------------------------------------

_ML_KEM_ALGORITHM:   str = "ML-KEM-768"  # FIPS 203 — NIST security level 2 (128-bit PQC)
_NONCE_SIZE_BYTES:   int = 12             # 96-bit nonce — GCM standard recommendation
_AES_KEY_SIZE_BYTES: int = 32             # ML-KEM-768 shared secret is always 32 bytes


# -------------------------------------------------------------------------
# Custom Exceptions
# -------------------------------------------------------------------------

class MLKEMKeypairError(Exception):
    """Raised when ML-KEM keypair generation fails."""
    pass


class MLKEMEncryptionError(Exception):
    """Raised when ML-KEM encapsulation or AES-256-GCM encryption fails."""
    pass


class MLKEMDecryptionError(Exception):
    """
    Raised when ML-KEM decapsulation or AES-256-GCM decryption fails.
    Covers wrong private key, tampered KEM ciphertext, and failed GCM tag
    verification — all treated as hard authentication failures.
    """
    pass


# -------------------------------------------------------------------------
# Keypair Generation
# -------------------------------------------------------------------------

def generate_keypair() -> tuple[bytes, bytes]:
    """
    Generate an ephemeral ML-KEM-768 keypair for one send session.

    Called by tqr.py before encrypt(). The public key is passed into encrypt().
    The private key is returned to tqr.py, which routes it to portal_server.py
    for browser-side decapsulation. The private key is never written to disk or
    transmitted in the email.

    Returns:
        (public_key_bytes, private_key_bytes)
    """
    try:
        with oqs.KeyEncapsulation(_ML_KEM_ALGORITHM) as kem:
            public_key  = kem.generate_keypair()
            private_key = kem.export_secret_key()
        return public_key, private_key
    except Exception as exc:
        raise MLKEMKeypairError(
            f"ML-KEM-768 keypair generation failed: {exc}"
        ) from exc


# -------------------------------------------------------------------------
# Encrypt
# -------------------------------------------------------------------------

def encrypt(plaintext: bytes, public_key: bytes, private_key: bytes) -> dict:
    """
    Encrypt plaintext using ML-KEM-768 key encapsulation + AES-256-GCM.

    ML-KEM-768 encapsulates a 32-byte shared secret against the provided public key,
    producing a kem_ciphertext. The shared secret is used directly as the AES-256-GCM
    key — no KDF step, as ML-KEM shared secrets are already uniformly random bytes.
    A fresh 12-byte nonce is generated per call using os.urandom.

    The public_key is generated by generate_keypair() and passed in by tqr.py.
    This module never generates its own keypair — keypair lifetime is tqr.py's concern.

    Returns a dict extending the standard Level 1/2 contract with one additional field:

        {
            "ciphertext": bytes,         ← AES-GCM encrypted message payload
            "metadata": {
                "tqr_level":      3,
                "algorithm":      "ML-KEM-768+AES-256-GCM",
                "kem_ciphertext": str,   ← hex — travels in MIME; used by portal to decapsulate
                "nonce":          str,   ← hex — 12-byte AES-GCM nonce
                "tag":            str,   ← hex — 16-byte GCM authentication tag
            },
            "private_key": bytes,        ← Level 3 ONLY. Never transmitted. tqr.py routes
                                           this to portal_server.py for browser-side decrypt.
        }

    NOTE: The "private_key" key is absent from Level 1 and Level 2 results. tqr.py must
    check for its presence before dispatching to the portal layer.
    """
    try:
        # --- ML-KEM encapsulation ---
        with oqs.KeyEncapsulation(_ML_KEM_ALGORITHM) as kem:
            kem_ciphertext, shared_secret = kem.encap_secret(public_key)

        # --- AES-256-GCM encryption with shared secret as key ---
        nonce    = os.urandom(_NONCE_SIZE_BYTES)
        aesgcm   = AESGCM(shared_secret)
        combined = aesgcm.encrypt(nonce, plaintext, associated_data=None)

        # Split joined output: AESGCM.encrypt() appends the 16-byte GCM tag.
        ciphertext, tag = combined[:-16], combined[-16:]

    except MLKEMKeypairError:
        raise
    except Exception as exc:
        raise MLKEMEncryptionError(
            f"ML-KEM-768 + AES-256-GCM encrypt failed: {exc}"
        ) from exc

    return {
        "ciphertext": ciphertext,
        "metadata": {
            "tqr_level":      3,
            "algorithm":      "ML-KEM-768+AES-256-GCM",
            "kem_ciphertext": kem_ciphertext.hex(),
            "nonce":          nonce.hex(),
            "tag":            tag.hex(),
        },
            "private_key": private_key,  # ML-KEM secret key for decapsulation.
                                          # Passed to portal_server.py by tqr.py.
                                          # Never included in MIME or cert output.
    }


# -------------------------------------------------------------------------
# Decrypt
# -------------------------------------------------------------------------

def decrypt(
    ciphertext:         bytes,
    private_key:        bytes,
    kem_ciphertext_hex: str,
    nonce_hex:          str,
    tag_hex:            str,
) -> bytes:
    """
    Decrypt ML-KEM-768 + AES-256-GCM ciphertext.

    tqr.py retrieves the kem_ciphertext, nonce, and tag from the MIME metadata
    (via decapsulator.py) and the private key from the portal session store, then
    passes all of them here. This module never contacts the KME, portal, or MIME
    layer directly.

    Decapsulation recovers the shared secret, which is then used as the AES-256-GCM
    key to decrypt and authenticate the message ciphertext.

    Raises MLKEMDecryptionError on any failure — wrong key, tampered KEM ciphertext,
    or failed GCM tag. The caller must treat this as a hard failure.

    Returns the recovered plaintext as bytes.
    """
    try:
        kem_ciphertext = bytes.fromhex(kem_ciphertext_hex)
        nonce          = bytes.fromhex(nonce_hex)
        tag            = bytes.fromhex(tag_hex)

        # --- ML-KEM decapsulation: recover shared secret ---
        with oqs.KeyEncapsulation(_ML_KEM_ALGORITHM, secret_key=private_key) as kem:
            shared_secret = kem.decap_secret(kem_ciphertext)

        # --- AES-256-GCM decryption and authentication ---
        aesgcm    = AESGCM(shared_secret)
        combined  = ciphertext + tag
        plaintext = aesgcm.decrypt(nonce, combined, associated_data=None)

    except MLKEMDecryptionError:
        raise
    except Exception as exc:
        raise MLKEMDecryptionError(
            f"ML-KEM-768 + AES-256-GCM decrypt or authentication failed. "
            f"Private key or KEM ciphertext may be wrong, or payload tampered. "
            f"Detail: {exc}"
        ) from exc

    return plaintext
